//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public class WeaponSlot
{
	private bool isOccupied;
	private Gem gem;	
	private bool isUnlocked;

	public WeaponSlot (bool isLock)
	{
		isOccupied = false;
		isUnlocked = isLock;

	}

	public bool IsOccupied {
		get {
			return isOccupied;
		}
		set {
			isOccupied = value;
		}
	}

	public Gem Gem {
		get {
			return gem;
		}
		set {
			gem = value;
		}
	}

	public bool IsUnlocked {
		get {
			return isUnlocked;
		}
		set {
			isUnlocked = value;
		}
	}
}

