//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

public class Skill
{
	private string name;
	private string desc;
	private int level;
	private int type;
	private SkillEffect effect;
	private bool isUnlocked;
	private string[] linesFromFile;
	private bool isSelected;
	private float cooldown;

	public Skill (int level, string nm)
	{
		this.name = nm;
		this.level = level;
		isUnlocked = false;
		isSelected = false;
		InitializeSkill ();
		//Debug.Log ("Skill initilaized !");
		//Debug.Log (name + " " + desc + " " + effect.Amount);
	}

	private void InitializeSkill(){
		linesFromFile = null;
		TextAsset txt = (TextAsset)Resources.Load ("Data/Skill/"+ name.Trim(), typeof(TextAsset));
		string content = txt.text;
		linesFromFile = content.Split ("\n" [0]);
		desc = linesFromFile [0];
		int.TryParse(linesFromFile [1],out type);
		effect = new SkillEffect (int.Parse(linesFromFile [2]),
		                          int.Parse(linesFromFile [3]));
		cooldown = float.Parse (linesFromFile [4]);
	}

	public bool IsSelected {
		get {
			return isSelected;
		}
		set {
			isSelected = value;
		}
	}

	public SkillEffect Effect {
		get {
			return effect;
		}
		set {
			effect = value;
		}
	}

	public string Name {
		get {
			return name;
		}
		set {
			name = value;
		}
	}

	public string Desc {
		get {
			return desc;
		}
		set {
			desc = value;
		}
	}

	public int Level {
		get {
			return level;
		}
		set {
			level = value;
		}
	}

	public int Type {
		get {
			return type;
		}
		set {
			type = value;
		}
	}

	public bool IsUnlocked {
		get {
			return isUnlocked;
		}
		set {
			isUnlocked = value;
		}
	}

	public float Cooldown {
		get {
			return cooldown;
		}
		set {
			cooldown = value;
		}
	}
}

